config/routes.rb
Rails.application.routes.draw do
  get 'games/games'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  get 'new' => 'games#new', as: :new
  post 'score' => 'games#score', as: :score

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
require 'open-uri'
require 'json'

API = 'https://wagon-dictionary.herokuapp.com/'
# frozen_string_literal: true

# app/controller/questions_controller.rb
class GamesController < ApplicationController
  def new
    letters = ('a'..'z').to_a
    @grid_letter = Array.new(10) { letters.sample }
  end

  def score
    valid = 0
    attempt = params[:word]
    @msg = "Sorry but #{attempt} does not seem to be a valid english word..."
    grid_copy = params[:grid]
    response_serialized = JSON.parse(URI.open("#{API}#{attempt}").read)
    attempt.downcase.chars.each { |chr| grid_copy.include?(chr) ? grid_copy.sub!(chr, '@') : valid += 1 }
    @msg = "Sorry but #{attempt} can't be built out of #{params[:grid]}" unless valid.zero?
    @msg = "Congratulation! #{attempt} is a valid English word!" if response_serialized['found'] && valid.zero?
    @file = params[:word]
    # raise
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/new.html.erb
<h1>New Game</h1>
<div class="grid_letter">
  <% @grid_letter.each do |letter| %>
    <div class="letter"><%= letter %></div>
  <% end  %>
  <p>What is the longest word you can find</p>
  <form action="/score" method="post" data-turbo="false">
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <%= hidden_field_tag 'grid', "#{@grid_letter.join}"  %>
    <input type="text" class="form-control" name="word">
    <input type="submit" class="btn btn-primary" value="submit">
  </form>
</div>
<%= form_with(url: score_path, method: :post) do |form| %>
  <div class="form-group">
    <%= text_field_tag 'word' %>
    <%= hidden_field_tag 'grid', "#{@grid_letter.join}" %>
  </div>
  <button type="submit" class="btn btn-primary">Enviar</button>
<% end %>

app/views/games/scrore.html.erb
<h1>Result</h1>
<%= @msg %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>